### ISSUE TITLE
onUseWith BUG

### ISSUE THREAD

**Issue by tiothiago** [Frowsty/OTCV8-Combobot#1]
The code below thats inside the combobot.lua file does not work properly.
I made various tests and the problem seems to be with the position that is sent with the command BotServer.send("useWith", {position = pos, id = itemId}). When I print pos.x, pos.y and pos.z it results in positions like: x = 65535, y = 64, z = 7.

 ` 
BotServer.listen("onUseWith", function(name, message)
          if storage.comboLeader then
            if name:lower() == storage.comboLeader:lower() then
              local tile = g_map.getTile(message.position)
              if tile and followMacro.isOn() then
                useWith(message.id)
              end
            end
          end
 end)

local useWithList = {3003, 646}

onUseWith(function(pos, itemId, target, subType)
    info("onUseWith " .. itemId)
    if allowFollow == "on" and BotServer._websocket and isInComboTeam then
      if table.find(useWithList, itemId) then
        BotServer.send("useWith", {position = pos, id = itemId})
      end
    end
  end)`

**Comment by Frowsty** [comment]
The issue looks to be that I'm accidentally sending "useWith" to the bot server rather than "onUseWith", I updated the script. It should work fine.
